
# General Site Settings
title: Team 3211 Documentation
description: Technical resources and mechanics for the Y-Team.
theme: just-the-docs

# Enable the navigation sidebar
nav_enabled: true

# Search settings (Optional but recommended)
search_enabled: true
search:
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Use the dark color scheme by default
color_scheme: dark

# Setting the URL helps with absolute links
url: "https://yteam3211.github.io"

sidebar_nav:
  - title: Home
    url: /index.html