# General Site Settings
title: Team 3211 Documentation
description: Technical resources and mechanics.
theme: just-the-docs
color_scheme: dark

# YOUR SIDEBAR MENU
sidebar_nav:
  - title: Home
    url: /index.html
  - title: Mechanics
    url: /mechanics.html
  - title: Shooter Assemblies
    url: /shooters.html
  - title: Control Software
    url: /software.html